apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odbxe-poc-pvc
  namespace: odbpoc
spec:
  storageClassName: default
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi