apiVersion: v1
kind: Service
metadata:
  name: oracle-db-xe
  namespace: odbpoc
spec:
  selector:
    app: odbxe
  ports:
  - name: listener
    port: 1521
    targetPort: 1521
  - name: manager
    port: 5500
    targetPort: 5500