apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db-xe
  namespace: odbpoc
  labels:
    app: odbxe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odbxe
  template:
    metadata:
      labels:
        app: odbxe
    spec:
      containers:
      - command:
        - /opt/oracle/runOracle.sh
      env:
        - name: ORACLE_PWD
          valueFrom:
          secretKeyRef:
            name: odbxe-admin
            key: ORACLE_PWD
        - name: ORACLE_CHARACTERSET
          valueFrom:
            configMapKeyRef:
              name: odbxe-config
              key: ORACLE_CHARACTERSET
        name: odbxe
        image: berkayoz/odbxe:18.4.0
        imagePullPolicy: Always
        ports:
        - containerPort: 1521
          name: listener
        - containerPort: 5500
          name: manager
        volumeMounts:
        - mountPath: /opt/oracle/oradata
          name: odbxe-poc-data
        securityContext:
          fsGroup: 54321
      volumes:
      - name: odbxe-poc-data
        persistentVolumeClaim:
          claimName: odbxe-poc-pvc
      restartPolicy: Always